'use client'
import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react'
import { supabase } from '@/lib/supabase'
import type { User as SupabaseUser } from '@supabase/supabase-js'
export interface UserProfile { id:string; email:string; name:string; avatarUrl:string|null; provider:'password'|'google'|'github'; role:'customer'|'admin'; joinedAt:string; updatedAt:string }
export interface PurchaseRecord { id:string; userId:string; bookId:string; title:string; author?:string; format?:string; downloadUrl:string; storagePath?:string; fileSize?:string; purchasedAt:string; price?:number; coverImage?:string }
export interface OrderRecord { id:string; userId:string; orderNumber:string; date:string; total:number; status:'Completed'|'Processing'; items?:Array<{title:string;quantity:number;price:number}> }
export type AuthScreen='login'|'signup'|'forgot-password'|'reset-password'|'magic-link'; export type AccountTab='account'|'purchases'|'orders'|'wishlist'
interface AuthContextType { user:UserProfile|null; authUser:SupabaseUser|null; isLoading:boolean; isAuthModalOpen:boolean; isAccountModalOpen:boolean; currentScreen:AuthScreen; activeAccountTab:AccountTab; wishlist:string[]; purchases:PurchaseRecord[]; orders:OrderRecord[]; openAuth:(s?:AuthScreen)=>void; openLogin:()=>void; openSignUp:()=>void; closeAuth:()=>void; setScreen:(s:AuthScreen)=>void; openAccountDashboard:(t?:AccountTab)=>void; closeAccountDashboard:()=>void; loginWithPassword:(e:string,p:string)=>Promise<{success:boolean;error?:string}>; loginWithMagicLink:(e:string)=>Promise<{success:boolean;message?:string;error?:string}>; signUpWithPassword:(n:string,e:string,p:string)=>Promise<{success:boolean;error?:string}>; loginWithOAuth:(p:'google'|'github')=>Promise<{success:boolean;error?:string}>; requestPasswordReset:(e:string)=>Promise<{success:boolean;message?:string;error?:string}>; resetPassword:(p:string)=>Promise<{success:boolean;error?:string}>; logout:()=>Promise<void>; toggleWishlist:(id:string)=>Promise<void>; isInWishlist:(id:string)=>boolean }
export const DEFAULT_ADMIN_EMAIL='portfolio.ankit.in@gmail.com'; export const DEFAULT_ADMIN_PASSWORD=''; export const DESIGNATED_ADMIN_EMAILS=['portfolio.ankit.in@gmail.com','ankit.portfolio.in@gmail.com','digitalankit21@gmail.com'];
export function isDesignatedAdmin(email?:string|null){ return !!email && DESIGNATED_ADMIN_EMAILS.includes(email.trim().toLowerCase()) }
const AuthContext=createContext<AuthContextType|undefined>(undefined)
function friendly(err:any){ return err?.message || 'Authentication failed. Please try again.' }
async function profileFor(authUser:SupabaseUser, fallbackName?:string):Promise<UserProfile>{
 const now=new Date().toISOString(), email=authUser.email||'', { data: existing }=await supabase.from('profiles').select('*').eq('id',authUser.id).maybeSingle(); const admin=isDesignatedAdmin(email) || existing?.role==='admin' || !!(await supabase.from('admins').select('id').eq('id',authUser.id).eq('enabled',true).maybeSingle()).data
 const row={ id:authUser.id, email, name:existing?.name || authUser.user_metadata?.name || fallbackName || email.split('@')[0] || 'Reader', avatar_url:authUser.user_metadata?.avatar_url || existing?.avatar_url || null, provider:authUser.app_metadata?.provider || 'password', role:admin?'admin':'customer', joined_at:existing?.joined_at || authUser.created_at || now, updated_at:now }
 await supabase.from('profiles').upsert(row,{onConflict:'id'}); if(admin) await supabase.from('admins').upsert({id:authUser.id,email,role:'admin',enabled:true},{onConflict:'id'}); return {id:row.id,email:row.email,name:row.name,avatarUrl:row.avatar_url,provider:(row.provider as any),role:row.role as any,joinedAt:row.joined_at,updatedAt:row.updated_at}
}
export function AuthProvider({children}:{children:ReactNode}){
 const [user,setUser]=useState<UserProfile|null>(null),[authUser,setAuthUser]=useState<SupabaseUser|null>(null),[isLoading,setLoading]=useState(true),[isAuthModalOpen,setAuthOpen]=useState(false),[isAccountModalOpen,setAccountOpen]=useState(false),[currentScreen,setScreen]=useState<AuthScreen>('login'),[activeAccountTab,setTab]=useState<AccountTab>('account'),[wishlist,setWishlist]=useState<string[]>([]),[purchases,setPurchases]=useState<PurchaseRecord[]>([]),[orders,setOrders]=useState<OrderRecord[]>([])
 const loadData=useCallback(async(id:string)=>{ const [{data:w},{data:p},{data:o}]=await Promise.all([supabase.from('wishlist').select('book_id').eq('user_id',id),supabase.from('purchases').select('*').eq('user_id',id).order('purchased_at',{ascending:false}),supabase.from('orders').select('*').eq('user_id',id).order('date',{ascending:false})]); setWishlist((w||[]).map(x=>x.book_id)); setPurchases((p||[]).map((x:any)=>({id:x.id,userId:x.user_id,bookId:x.book_id,title:x.title,author:x.author,format:x.format,downloadUrl:x.download_url||'',storagePath:x.storage_path,purchasedAt:x.purchased_at,price:x.price,coverImage:x.cover_image}))); setOrders((o||[]).map((x:any)=>({id:x.id,userId:x.user_id,orderNumber:x.order_number,date:x.date,total:Number(x.total),status:x.status,items:x.items}))) },[])
 const apply=useCallback(async(u:SupabaseUser|null)=>{setAuthUser(u); if(u){setUser(await profileFor(u)); await loadData(u.id)}else{setUser(null);setWishlist([]);setPurchases([]);setOrders([])} setLoading(false)},[loadData])
 useEffect(()=>{ supabase.auth.getSession().then(({data})=>apply(data.session?.user||null)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>apply(s?.user||null)); return()=>subscription.unsubscribe() },[apply])
 const loginWithPassword=async(email:string,pass:string)=>{const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password:pass}); if(error)return{success:false,error:friendly(error)}; await apply(data.user); setAuthOpen(false); return{success:true}}
 const loginWithMagicLink=async(email:string)=>{const {error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:typeof window!=='undefined'?`${window.location.origin}/account`:undefined}}); if(error)return{success:false,error:friendly(error)}; return{success:true,message:'Magic link sent! Check your inbox to sign in with one click.'}}
 const signUpWithPassword=async(name:string,email:string,pass:string)=>{const {data,error}=await supabase.auth.signUp({email:email.trim(),password:pass,options:{data:{name:name.trim()}}}); if(error)return{success:false,error:friendly(error)}; if(data.user) {await apply(data.user);setAuthOpen(false)} return{success:true}}
 const loginWithOAuth=async(provider:'google'|'github')=>{const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:typeof window!=='undefined'?window.location.origin:'/'}}); return error?{success:false,error:friendly(error)}:{success:true}}
 const requestPasswordReset=async(email:string)=>{const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:typeof window!=='undefined'?`${window.location.origin}/`:'/' }); return error?{success:false,error:friendly(error)}:{success:true,message:'If that email is in our system, we sent a password reset link.'}}
 const resetPassword=async(password:string)=>{const {error}=await supabase.auth.updateUser({password});return error?{success:false,error:friendly(error)}:{success:true}}
 const logout=async()=>{await supabase.auth.signOut();setAccountOpen(false)}
 const toggleWishlist=async(bookId:string)=>{if(!user){openLogin();return} const added=wishlist.includes(bookId); setWishlist(x=>added?x.filter(i=>i!==bookId):[...x,bookId]); const result=added?await supabase.from('wishlist').delete().eq('user_id',user.id).eq('book_id',bookId):await supabase.from('wishlist').insert({user_id:user.id,book_id:bookId}); if(result.error)setWishlist(x=>added?[...x,bookId]:x.filter(i=>i!==bookId))}
 const openAuth=(s:AuthScreen='login')=>{setScreen(s);setAuthOpen(true)}; const openLogin=()=>openAuth('login'); const openSignUp=()=>openAuth('signup'); const closeAuth=()=>setAuthOpen(false); const openAccountDashboard=(t:AccountTab='account')=>{setTab(t);setAccountOpen(true)}; const closeAccountDashboard=()=>setAccountOpen(false)
 return <AuthContext.Provider value={{user,authUser,isLoading,isAuthModalOpen,isAccountModalOpen,currentScreen,activeAccountTab,wishlist,purchases,orders,openAuth,openLogin,openSignUp,closeAuth,setScreen,openAccountDashboard,closeAccountDashboard,loginWithPassword,loginWithMagicLink,signUpWithPassword,loginWithOAuth,requestPasswordReset,resetPassword,logout,toggleWishlist,isInWishlist:(id)=>wishlist.includes(id)}}>{children}</AuthContext.Provider>
}
export function useAuth(){const c=useContext(AuthContext);if(!c)throw new Error('useAuth must be used within an AuthProvider');return c}
